FROM python:3.11.4-slim-bullseye

# prevents python buffering stdout and stderr  
ENV PYTHONUNBUFFERED 1  
  
# prevents python from writing .pyc files to disc  
ENV PYTHONDONTWRITEBYTECODE 1  
  
# sets up the working directory for any RUN, CMD, ENTRYPOINT, COPY and ADD instructions   
WORKDIR /app

COPY ./requirements.txt .

# install system dependencies 
RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential && pip install -r requirements.txt

# copies files and directories from current directory to WORKDIR  
COPY . .

COPY ./compose/start.sh /start.sh
  
RUN sed -i 's/\r$//g' /start.sh && chmod +x /start.sh
